version: '3'
services:
  app:
    build: ./docker/app/
    ports:
      - '9999:3000'
    volumes:
      - ./app:/app
    command: bash
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
